version: '3.9'
services:
  db:
    image: postgres:15.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=foobarbaz
    ports:
      - 5432:5432
    restart: unless-stopped
volumes:
  pgdata:
